<?
$title = "WordBib";
include("../elements/prefix.inc");
?>

<p>
	WordBib is a bibliography program for Microsoft Word, which (surprisingly!) lacks a bibliography feature. First read the information on the style generated by WordBib - if its not what you like then don't both installing it. If it does meet you needs, then download, install and use it. WordBib is both free and open source.
</p>

<h2>What WordBib gives you</h2>

<p>
	Consider the following snippet of text, its typical of the kind of thing WordBib might give you.
</p>

<div style="font-family:times new roman,serif;margin:15px;border:1px solid black;padding:5px;">
	This is my thesis in which I cite things.<br/>
	<br/>
	It was remarked by Turing [1] that the thing is true, however Godel [2] disagreed.<br/>
	<br/>
	Comparing the arguments, those presented in [1,3] can be seen as accurate.<br/>
	<br/>
	<b>Bibliograph</b><br/>
	1. Turing<br/>
	2. Godel<br/>
	3. A N Other
</div>

<p>
	The things to note are that WordBib automatically puts your references in order of citation, for example if you move the citation of Godel to be first, all the other citations will renumber, as will the bibliograph. WordBib also gives a lot of flexibility as to the format of the numbers, {1}, 1., #1, [1,2,3] are all valid ways of using WordBib.
</p>

<h2>Installing WordBib</h2>

<p>
	Unfortunately this isn't particularly easy, but only needs to be done once per machine. If you have written your document using WordBib, and it is openned/printed on another machine it will work just fine even with WordBib not installed.
</p>
<ol>
	<li>Download WordBib, from <a href="projects/WordBib.bas">here</a>. Save it to disk.</li>
	<li>Start Microsoft Word.</li>
	<li>Tools / Macros / Visual Basic Editor.</li>
	<li>File / Import File, browse to WordBib.bas.</li>
	<li>File / Close and return to Word.</li>
	<li>Tools / Customize.</li>
	<li>Commands tab / Macros / Normal.WordBib.UpdateBib - drag and drop onto a toolbar.</li>
	<li>Right click on the added button to give it a name and icon.</li>
	<li>All done.</li>
</ol>

<h2>Using WordBib</h2>

<p>
	WordBib makes use of the Word comment feature, so you might need to get a bit more familiar with that. To insert a reference, in your document do the following.
</p>
<ol>
	<li>Type the style of the reference you want with 0 as the number, i.e. "[0]".</li>
	<li>Select the text of the reference.</li>
	<li>Insert / Comment.</li>
	<li>As the text of the comment, type "Turing", this refers to the appropriate reference.</li>
	<li>Now click the UpdateBib button you added during the installation, note it says you haven't defined Turing.</li>
	<li>Now skip to the end of the document and add the citation, "0. Turing, A Paper".</li>
	<li>Select the number bit of the reference, and add a comment.</li>
	<li>As the text of the comment, type "!Turing".</li>
	<li>Click UpdateBib again.</li>
	<li>Note that the references are correct, to both refer to 1.</li>
</ol>
<p>
	Now you have leart WordBib, just make your changes, give every reference a unique name, which you refer to it by, and it should keep track of the rest. When you feel like it, just click on UpdateBib, and WordBib will sort it all out.
</p>

<? include("../elements/suffix.inc") ?>
